### PR TITLE
Ao/postman codelab

### PR DESCRIPTION
**Pull request by ahmet269**
This codelab is about how to connect and raise CRUD operations for Power App Instance using Postman.

### CODE REVIEW

**Comment by tdashworth** [comment]
@ahmet269 @markcunninghamuk - great work on this! Were you lucky or did you test the site generation locally as we often had issues?

**Comment by ahmet269** [comment]
Hey Tom,I run it locally using npm run serve. I usually won't rely on luck when it comes to things like this. On 29 Nov 2021 08:55, Tom Ashworth ***@***.***> wrote:
@ahmet269 @markcunninghamuk - great work on this! Were you lucky or did you test the site generation locally as we often had issues?

**Comment by markcunninghamuk** [comment]
Who needs luck when you have pure skill..

**Comment by ahmet269** [comment]
Exactly On 29 Nov 2021 16:34, Mark Cunningham ***@***.***> wrote:
Who needs luck when you have pure skill.. :)

**Pull request merged**
